---
layout: topic
title: "Setting up your computer"
output: html_document
---

### R and RStudio

**R** and **RStudio** are separate downloads and installations. R is the underlying statistical computing environment, but using R alone is no fun. RStudio is a graphical integrated development environment (IDE) that makes using R much easier and more interactive. You need to install R before you install RStudio. In the sections below are the instructions for installing R and R Studio on your operating system.

#### Windows

##### If you already have R and RStudio installed

* Open RStudio, and click on "Help" > "Check for updates". If a new version is
	available, quit RStudio, and download the latest version for RStudio.
* To check which version of R you are using, start RStudio and the first thing
  that appears in the console indicates the version of R you are
  running. Alternatively, you can type `sessionInfo()`, which will also display
  which version of R you are running. Go on
  the [CRAN website](https://cran.r-project.org/bin/windows/base/) and check
  whether a more recent version is available. If so, please download and install
  it. You can [check here](https://cran.r-project.org/bin/windows/base/rw-FAQ.html#How-do-I-UNinstall-R_003f) for
  more information on how to remove old versions from your system if you wish to do so.

##### If you don't have R and RStudio installed

* Download R from
  the [CRAN website](http://cran.r-project.org/bin/windows/base/release.htm).
* Run the `.exe` file that was just downloaded
* Go to the [RStudio download page](https://www.rstudio.com/products/rstudio/download/#download)
* Under *Installers* select **RStudio x.yy.zzz - Windows
  XP/Vista/7/8** (where x, y, and z represent version numbers)
* Double click the file to install it
* Once it's installed, open RStudio to make sure it works and you don't get any
  error messages.


#### macOS

##### If you already have R and RStudio installed

* Open RStudio, and click on "Help" > "Check for updates". If a new version is
	available, quit RStudio, and download the latest version for RStudio.
* To check the version of R you are using, start RStudio and the first thing
  that appears on the terminal indicates the version of R you are running. Alternatively, you can type `sessionInfo()`, which will also display which version of R you are running. Go on
  the [CRAN website](https://cran.r-project.org/bin/macosx/) and check
  whether a more recent version is available. If so, please download and install
  it.

##### If you don't have R and RStudio installed

* Download R from
  the [CRAN website](http://cran.r-project.org/bin/macosx).
* Select the `.pkg` file for the latest R version
* Double click on the downloaded file to install R
* It is also a good idea to install [XQuartz](https://www.xquartz.org/) (needed
  by some packages)
* Go to the [RStudio download page](https://www.rstudio.com/products/rstudio/download/#download)
* Under *Installers* select **RStudio x.yy.zzz - Mac OS X 10.6+ (64-bit)**
  (where x, y, and z represent version numbers)
* Double click the file to install RStudio
* Once it's installed, open RStudio to make sure it works and you don't get any
  error messages.


#### Linux

* Follow the instructions for your distribution
  from [CRAN](https://cloud.r-project.org/bin/linux), they provide information
  to get the most recent version of R for common distributions. For most
  distributions, you could use your package manager (e.g., for Debian/Ubuntu run
  `sudo apt-get install r-base`, and for Fedora `sudo yum install R`), but we
  don't recommend this approach as the versions provided by this are
  usually out of date. In any case, make sure you have at least R 3.3.1.
* Go to the
  [RStudio download page](https://www.rstudio.com/products/rstudio/download/#download)
* Under *Installers* select the version that matches your distribution, and
  install it with your preferred method (e.g., with Debian/Ubuntu `sudo dpkg -i
  rstudio-x.yy.zzz-amd64.deb` at the terminal).
* Once it's installed, open RStudio to make sure it works and you don't get any
  error messages.


### Editing the Course Website

The course website can be edited by changing the html files in the course GitHub repository located at https://github.com/FukamiLab/BIO202.

#### If you don't want to work with git

1. Go to the course GitHub repository above.
2. Click on the .Rmd file for the lesson you want to edit.
3. Click the Raw button in the upper right corner.
4. When the page with text opens, download the file and save it as a .Rmd file. Make sure to remove any .txt extensions that may be automatically added.
5. Open and edit the .Rmd file in R Studio. Use the 'Knit' button to convert the file to an html to check your changes.
6. When you as satisfied, email the .Rmd file to Jes no later than 8 am on the day you present.


#### If you are new to git, but want to learn

See the section below on installing git on your computer.

Attend the git tutorial provided at the beginning of class.

Use the 'If you are familiar with git' workflow below to make changes to the course website.


#### If you are familiar with git


The general workflow is:

1. If you have not aready done so, fork the repository from https://github.com/FukamiLab/BIO202 to your account on GitHub. Then clone a local copy of this forked repository (from your own GitHub account) to your computer. [Instructions](). This only needs to be done once.
2. Before you start working:
  + Make sure your copy is up to date with the FukamiLab repository on GitHub. If not, submit a Pull request to update it. [Instructions]()
  + Make sure your local repository on your computer is up to date with your fork of the repository on your GitHub account using `git pull`.
3. Work on the .Rmd file for your lesson in R Studio on your computer. Click 'Knit' to render your changes as an html file and view them in your browser. Note that any edits you make are only on your computer until you submit a pull request to merge your changes to the repository. Make sure that when you have made your last edit to the .Rmd file you click 'Knit' so that an up-to-date html file is generated. The html file will be the one that appears on the website.
4. Commit the changes you make periodically to your local repository using `git commit -m "changes you made"`.
5. When you are finished, push the commits from your local repository to your fork on your GitHub account using `git push origin master`.
6. Submit a pull request on GitHub to merge the changes on your fork with the original BIO202 repository on FukamiLab no later than 8 am on the day you present. Jes or Tad will approve your pull request.




### git


TO DO: 

* INCLUDE INSTRUCTIONS FOR DOWNLOADING GIT AND INTEGRATING WITH RSTUDIO
* Link to git lesson content on SWC



#### Attribution

The content of this webpage was derived from [Data Carpentry](http://datacarpentry.org) materials (Copyriright (c) Data Carpentry) under CC-3.0 Attribution License (see [http://creativecommons.org/licenses/by/3.0/](http://creativecommons.org/licenses/by/3.0/)). 
