---
layout: topic
title: "Student Projects"
author: Jes & Tad
output: html_document
---

```{r include = FALSE}
# This code block sets up the r session when the page is rendered to html
# include = FALSE means that it will not be included in the html document

# Write every code block to the html document 
knitr::opts_chunk$set(echo = TRUE)

# Write the results of every code block to the html document 
knitr::opts_chunk$set(eval = TRUE)

# Define the directory where images generated by knit will be saved
knitr::opts_chunk$set(fig.path = "images/")

# Set the web address where R will look for files from this repository
# Do not change this address
repo_url <- "https://raw.githubusercontent.com/fukamilab/BIO202/master/"
```

#### Anna

**Spatiotemporal Analysis of the San Francisco Estuary Water Column Microbiome**

I will explore environmental drivers on archaeal and bacterial communities in bottom waters of San Francisco Bay using 16S rRNA amplicon libraries and geochemical water column data from USGS water quality cruises.


#### Beth

**The role of evolutionary history in network response to agricultural development**

Species traits are often influenced by evolutionary history, and in plant-pollinator networks, certain species interaction traits may make species more or less vulnerable to a major disturbance like agricultural development. Thus, I want to know whether there is a phyogenetic signal in species interaction traits, and whether a nonrandom loss of phylogenetic diversity leads to predictable changes in overall plant-pollinator network structure. 


#### Jamie

**Disentangling the importance of drivers that structure benthic communities**  

Determine what environmental and biological factors drive benthic community structure and how their importance varies spatially (i.e. local to regional), using data from 12 habitat types in the Bahamas.  

#### Lizzie

**Project Title**

Brief description of the question you want to ask and the data you have to analyze it.


#### Marissa

**Yellow fever and dengue interactions in Brazil**

Using monthly human case data of yellow fever and dengue in Brazil, I will analyze the spatial trends of the two diseases to identify whether immunity dynamics with dengue contribute to determining the spatial distribution of yellow fever virus. 


#### Meghan

**Land Use as Driver of Aedes vector mosquito distribution in Costa Rica**

I will assess how environmental characteristics drive Aedes aegypti and albopictus distribution by comparing field-collected mosquito data from a land use gradient, field-collected temperature and humidity data from those sites, and remote sensing data of environmental characteristics of those sites.


#### Nicole

**Project Title**

Brief description of the question you want to ask and the data you have to analyze it.


#### Priscilla

**Project Title**

Brief description of the question you want to ask and the data you have to analyze it.


#### Sandra

Spatial autocorrelation in a Pennsylvanian swamp forest

I want to interrogate patterns of spatial autocorrelation of plants in a Paleozoic forest, at multiple taxonomic levels. I will use semi-quantitative data collected in a transect through a coal mine.


#### Tyler

**Effects of anthropogenic disturbance on the structure of species interaction networks**


How does anthropogenic disturbance affect the structure of species interaction networks? We (Beth and I) have compiled a database of ~30 published datasets which examine changes in network structure across different levels of disturbance. Each dataset consists of two or more species interaction networks measured at study sites exhibiting different levels of anthropogenic disturbance (such as fragmentation, defaunation, invasive species, etc.). We will use network analysis to quantify the structure of each network, and then use meta-analytical techniques to draw conclusions about the general effects of distrubance on network structure across the ~30 datasets.


#### Nick

**Response of species traits to deforestation and agricultural intensification in Costa Rica**


Which traits make birds most susceptible to deforestation and agricultural intensification? Here I plan to use bird banding data from southern Costa Rica in combination with species and individual-level traits and environmental covariates to address this question.


