---
layout: topic
title: "GLM with count, binary. and proportional data"
author: Tad and Meghan Howard
output: html_document
---

**Assigned Reading:**

> Chapters 9 & 10 from: Zuur, A. F., Ieno, E. N., Walker, N., Saveliev, A. A. and Smith, G. M. 2009. *Mixed Effects Models and Extensions in Ecology with R.* Springer. [link](https://link-springer-com.stanford.idm.oclc.org/book/10.1007%2F978-0-387-87458-6)


```{r include = FALSE}
# This code block sets up the r session when the page is rendered to html
# include = FALSE means that it will not be included in the html document

# Write every code block to the html document 
knitr::opts_chunk$set(echo = TRUE)

# Write the results of every code block to the html document 
knitr::opts_chunk$set(eval = TRUE)

# Define the directory where images generated by knit will be saved
knitr::opts_chunk$set(fig.path = "images/04-B/")

# Set the web address where R will look for files from this repository
# Do not change this address
repo_url <- "https://raw.githubusercontent.com/fukamilab/BIO202/master/"
```

### Key Points

#### Poisson GLM for count data, without overdispersion

* `family = poisson`

* Model selection: AIC or hypothesis testing (z-statistics, `drop1()`, `anova()`)

* Model validation: Use normalized (or Pearson) residuals (as in Ch 4) or deviance residuals (default in R), which give similar results (except for zero-inflated data).

* Overdispersion (variance is larger than mean): Needs correction when Phi (= D/(n-P)) > 1.5, and quick fix is to use `family = quasipoisson`, but cost is that se of parameters will be multiplied by sqrt(Phi).

#### Negative binomial GLM for count data, with overdispersion

+ Use when Phi > 15

+ `glm.nb()` in `library(MASS)` (Modern Applied Statistics with S)

+ Advantage of NB over quasipoisson: `step()` and `stepAIC()` can be used for model selection

+ There can be overdispersion in NB GLM, but options for fixing it are scarse in R.

+ Offset: equation 9.18 on p. 240

     `L0 <- glm(Copepod ~ offset(LVol) + fStation, family = poisson, data = Lice)`

#### Bernoulli GLM for binary (presence-absence) data

+ Table 10.1: getting rid of lower (0) and upper (1) bounds of probabilities

+ `family = binomial`
   
   * `family = binomial(link="probit")`

   * `family = binomial(link="cloglog")` - when there are many zeros or many ones

+ Bernoulli GAM (Fig 10.6)

#### Binomial GLM for proportional data

+ Model on p. 255: Yi ~ N(ni, pii)

+ `family=quasibinomial` for overdispersed data


***


### Analysis Example



### Discussion Questions





