---
layout: topic
title: "Spatial regression"
author: Jes & Marissa
output: html_document
---

**Assigned Reading:**

> Chapters 6 & 7 from: Zuur, A. F., Ieno, E. N., Walker, N., Saveliev, A. A. and Smith, G. M. 2009. *Mixed Effects Models and Extensions in Ecology with R.* Springer. [link](https://link-springer-com.stanford.idm.oclc.org/book/10.1007%2F978-0-387-87458-6)

**Optional Readings:**

> Beale, C. M., Lennon, J. J., Yearsley, J. M., Brewer, M. J. and Elston, D. A. 2010. Regression analysis of spatial data. *Ecology Letters* **13**: 246-264. [DOI: 10.1111/j.1461-0248.2009.01422.x](http://dx.doi.org/10.1111/j.1461-0248.2009.01422.x)
>
> Hawkins, B. A. 2012. Eight (and a half) deadly sins of spatial analysis. *Journal of Biogeography* **39**: 1-9. [DOI: 10.1111/j.1365-2699.2011.02637.x](http://dx.doi.org/10.1111/j.1365-2699.2011.02637.x)


```{r include = FALSE}
# This code block sets up the r session when the page is rendered to html
# include = FALSE means that it will not be included in the html document

# Write every code block to the html document 
knitr::opts_chunk$set(echo = TRUE)

# Write the results of every code block to the html document 
knitr::opts_chunk$set(eval = TRUE)

# Define the directory where images generated by knit will be saved
knitr::opts_chunk$set(fig.path = "images/08-B/")

# Set the web address where R will look for files from this repository
# Do not change this address
repo_url <- "https://raw.githubusercontent.com/fukamilab/BIO202/master/"
```

### Key Points

**General ideas**

+ Spatial and temporal autocorrelation can be problematic because they violate the assumption that the residuals in regression are independent, which causes estimated standard errors of parameters to be biased and causes parametric statistics no longer follow their expected distributions (i.e. p-values are too low).

+ Spatial dependence can be induced by both extrinsic and intrisic factors.

+ Spatial dependence can be modeled in many ways (see Table 2 in Beale et al. 2010) but we will talk about:
    + GLS: spatial dependence modeled by fitting a parametric model to the residuals
    + Spatial filters (PCNM or MEM): spatial structure extracted using ordination of locations and spatial eigenvectors included as covariates
    
**Definitions**

*stationarity* : when the mean, variance and correlation structure do not vary across time or space. We assume stationarity in the residuals of regression models. 

*isotropy* : when a process does not vary with direction (only with distance)

*lag* : the number of steps or links that separate two observations (an integer). For example, the lag between observations sampled in June and August would be 2, if samples are collected once a month, but it would be 1, if samples are collected every other month.

*autocorrelation function* : a function that gives the correlation between two observations as a function of the lag between them. Note: `acf()` takes a series of values and assumes that adjacent values are separated by a lag of 1.

*variogram* : a function that gives the variance between two observations as a function of the distance between them. A *semi-variogram* gives 1/2 of the variance (semivariance) and is usually what is given by stats programs. Note: variograms are parametric functions, whereas *empirical variograms* are estimated from data by grouping observations into short windows of the distance between them.

+ *sill* : the asymptotic value of the variance
+ *range* : the distance at which the variance reaches the asymptote
+ *nugget* : the variance between observations separated by a distance of zero (e.g. variance upon re-sampling)

**How to determine whether you should incorporate autocorrelation in a regression model**

1. Fit a model without autocorrelation.
2. Plot the residuals vs. the covariates along which you expect autocorrelation (e.g. time, x-y coordinates).
3. Plot the correlation among residuals vs. the distance between them. This could be the autocorrelation function, empirical variogram, or Moran's I at different distances (see Friday's reading).
4. Compare models that do and do not model the autocorrelation structure using AIC or other information criteria.

**Functions for modeling residual correlation structure**

| Name              | `correlation =` argument in  `gls()` | Explanation |
|-------------------|-----------------------------------|-------------|
| compound symmetry | `corCompSym(form =~ x)`           | The residual correlation is the same among all observations regardless of the distance between them. |
| autoregressive order 1 (AR-1) | `corAR1(form =~ x)`   | The residual correlation is the same ($\rho$) between all observations separated by a lag of 1 and the residual correlation between observations separated by a lag of $n$ is $\rho^n$. |
| autoregressive moving average ARMA(p,q) | `corARMA(start_p, start_q, p, q)` | An observation is a linear function of other observations with separate coeffients estimated for lags of $1$ to $p$ plus a linear function of the error of other observations with separate coefficients estimated for lags of $1$ to $a$ (effectively a more flexible model) |
| exponential correlation | `corExp(form =~ x + y)` | parametric model of the semi-variogram |
| Gaussian correlation | `corGaus(form =~ x + y)`| parametric model of the semi-variogram|
| linear correlation | `corLin(form =~ x + y)` | parametric model of the semi-variogram|
| rational quadratic correlation | `corRatio( form =~ x + y)` | parametric model of the semi-variogram|
| spherical correlation | `corSphere( form =~ x + y)` | parametric model of the semi-variogram|


Note:

+ The variogram models are parametrized by their sill, range, and nugget.
+ In the variogram models, distances are by default Euclidean ($\sqrt{x^2 + y^2}$) so you should not use latitude and longitude. UTM coordinates can be used instead since they are in meters.
+ If using a random-effects model, be sure to apply the correlation structure at the deepest level within groups so that the correlation between groups is zero. Do this using `form =~ x | group`.



### Analysis Example



### Discussion Questions





